### ISSUE TITLE
ODataQueryOptions.Filter Fails

### ISSUE THREAD

**Issue by vinaysharma77** [TrevorPilley/Net.Http.WebApi.OData#128]
Hello,
I'm running into two issues related to the filter parsing of ODataQueryOptions.

1. I'm supplying following filter - "$filter=CIF eq 12345678901" and I get exception - "System.OverflowException: Value was either too large or too small for an Int32". If I change the filter to "$filter=CIF eq 1234567890", so basically take one digit out and make the value 10 digit number, the Filter parsing works. So are we not honoring integer values larger than Int32? What if my value datatype is a Int64?

2. I supplied following filter - "$filter=ID eq 1234abcd". In this case my ID is actually of string datatype. But if I don't specify the value in single quote the Filter parsing logic just seem to trim the alpha portion of my value and takes 1234 as my value with a datatype of Int32. Why can't we take the entire value and see if its of type Int, only then consider as an integer value and if the value doesn't successfully gets parsed as Int then consider it as a string and take the entire value supplied as opposed to trimming the alpha portion out?

A quick response on this would be greatly appreciated!

Thanks in advance.

Vinay Sharma

**Comment by TrevorPilley** [comment]
Hi Vinay,

For your first question, you currently need to specifically state that the integer value is 64 bits not 32 bits by putting an L at the end:

> $filter=CIF eq 12345678901L

I will look at updating the parsing logic so that isn't necessary in a future version of the library.

For your second, if you want a value to be interpreted as a string it must be in single quotes as that is how a string is defined in the [OData ABNF](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt):

> $filter=ID eq '1234abcd'

(see) `string           = SQUOTE *( SQUOTE-in-string / pchar-no-SQUOTE ) SQUOTE`
