### ISSUE TITLE
Return 501 NOT IMPLEMENTED if a feature is not implemented by the service

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/Net.Http.WebApi.OData#65]
> Services that haven’t implemented a requested feature now have to respond with 501 Not
> Implemented.

**Comment by scullinan** [comment]
@TrevorPilley 501 is meant to be for unsupported methods across all resources. I believe the correct response should be a 400 bad request because the request is bad and it should not be repeated without modifications. 
A 5xx range implies that the issue is with the server and the client can do nothing about it which clearly would not be the case. 
A 4xx range implies the client has down something wrong and can address the issue.
I don't think you should implement this without it being either optional for the developer or customisable IMO.

**Comment by TrevorPilley** [comment]
@scullinan 501 means not implemented, if a client tries to use a feature which the server doesn't implement then it absolutely should return a 501 - it also states that in the OData spec - http://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html#_Toc366145446

**Comment by scullinan** [comment]
@TrevorPilley it is interesting that OData specifies this, I'd say they are perhaps over-reaching but I can see the logic i.e. that part of the spec is not implemented. RFC-2616 governs the HTTP Status codes and their definitions and taken literally it says it is for a not implemented request **method**. https://www.ietf.org/rfc/rfc2616.txt
I think this may come down to interpretation to some degree but I can see the merit in sticking to the OData spec, I'm just not sure that's what I'd like to do. I was just wondering if this could be optional or configurable?

**Comment by TrevorPilley** [comment]
My intention is for the library to be true to the specification otherwise what's the point in a spec if implementations vary...

It's true that all web based "REST" APIs are limited to the HTTP verbs and status codes but I think that 501 here is better than a 400 since 400 implies that the client sent an incorrect request and if it were modified may then work which wouldn't be the case if it is that the server doesn't actually implement the requested functionality.
