### ISSUE TITLE
Not parsing ampersand in query

### ISSUE THREAD

**Issue by roly445** [TrevorPilley/Net.Http.WebApi.OData#85]
Hi,

I'm trying to exectue the follow query `Business?$filter=LegacyId eq 2139 and Name eq 'Pool Farm & Primrose Hill Nursery'&$top=1` which I have url encoded to be `Business/Business?$filter=LegacyId%20eq%202139%20and%20Name%20eq%20%27Pool%20Farm%20%26%20Primrose%20Hill%20Nursery%27&$top=1` but the parsing seems to be terminating after the `&` in `Pool Farm &`.

I had a look at the code but I can't seem to find where this is happening.

**Comment by TrevorPilley** [comment]
It looks to be related to the encoding, the Filter parser can correctly parse `LegacyId eq 2139 and Name eq 'Pool Farm & Primrose Hill Nursery'` into the expression tree.

The problem is earlier than that when `ODataQueryOptions` splits the query parameters which is does on the `&` character after the query is URL decoded, I think that needs tweaking slightly and you'd need to encode the internals of the filter but not the URI entirely (something like `Business?$filter=LegacyId+eq+2139+and+Name+eq+'Pool+Farm+%26+Primrose+Hill+Nursery'&$top=1`

**Comment by roly445** [comment]
Thanks, I'll take a look.  I didn't think it would be an issue with microlite as its working very well for us.

On a different note, but something which might help me resolve this, do you know of any good .net client side libraries for OData query generation?

**Comment by roly445** [comment]
Not sure.  I have uploaded a screen of the ODataQueryOptions and it looks like the 'RawValues' its correct.

![odata](https://cloud.githubusercontent.com/assets/9212070/19806602/e2b596c4-9d13-11e6-83c4-7c8fafcf8564.PNG)

**Comment by TrevorPilley** [comment]
The problem is that it URL un-encodes the whole query string before doing the split on `&` to get each query option so instead of ending up with:

```
[0] $filter=LegacyId eq 2139 and Name eq 'Pool Farm & Primrose Hill Nursery'
[1] $top=1
```

It ends up with

```
[0] $filter=LegacyId eq 2139 and Name eq 'Pool Farm 
[1]  Primrose Hill Nursery'
[2] $top=1
```

And ignores the second part as it isn't an OData query option (since it doesn't start `$`) I've got a fix locally which I'm double checking, and derived an initial failing test from your initial example so if that's all OK I'll push an update over the weekend

**Comment by roly445** [comment]
Wow that's quick.  Thanks

**Comment by TrevorPilley** [comment]
Luckily I spotted the email at lunch time so had a few mins to look into it, keep your eye out for 3.3.7!
